<script lang="ts">
	import AiDoctorChat from '../../components/AiDoctorChat.svelte';
	import AiDoctorDisclaimer from '../../components/AiDoctorDisclaimer.svelte';
	import { disclaimerAccepted } from '$lib/aiDoctor/disclaimerStore';
</script>

<svelte:head>
	<title>The AI doctor</title>
	<meta
		name="description"
		content="A RAG chat over a personal library of papers and posts. Search runs in your browser over a locally-downloaded index; answers are generated by a hosted open-weights model, with citations."
	/>
</svelte:head>

{#if !$disclaimerAccepted}
	<AiDoctorDisclaimer />
{:else}
	<AiDoctorChat />
{/if}
